INSERT INTO PRODUCTS (PRODUCT_ID, PRODUCT_NAME, UNIT_PRICE, IMAGE_MIME_TYPE, IMAGE_FILENAME, IMAGE_CHARSET, IMAGE_LAST_UPDATED) VALUES (1,'Boy''s Shirt (White)',29.55,NULL,NULL,NULL,NULL);
INSERT INTO PRODUCTS (PRODUCT_ID, PRODUCT_NAME, UNIT_PRICE, IMAGE_MIME_TYPE, IMAGE_FILENAME, IMAGE_CHARSET, IMAGE_LAST_UPDATED) VALUES (2,'Women''s Shirt (Green)',16.67,NULL,NULL,NULL,NULL);
INSERT INTO PRODUCTS (PRODUCT_ID, PRODUCT_NAME, UNIT_PRICE, IMAGE_MIME_TYPE, IMAGE_FILENAME, IMAGE_CHARSET, IMAGE_LAST_UPDATED) VALUES (3,'Boy''s Sweater (Green)',44.17,NULL,NULL,NULL,NULL);
INSERT INTO PRODUCTS (PRODUCT_ID, PRODUCT_NAME, UNIT_PRICE, IMAGE_MIME_TYPE, IMAGE_FILENAME, IMAGE_CHARSET, IMAGE_LAST_UPDATED) VALUES (4,'Boy''s Trousers (White)',43.71,NULL,NULL,NULL,NULL);
INSERT INTO PRODUCTS (PRODUCT_ID, PRODUCT_NAME, UNIT_PRICE, IMAGE_MIME_TYPE, IMAGE_FILENAME, IMAGE_CHARSET, IMAGE_LAST_UPDATED) VALUES (5,'Girl''s Shorts (Red)',38.28,NULL,NULL,NULL,NULL);
INSERT INTO PRODUCTS (PRODUCT_ID, PRODUCT_NAME, UNIT_PRICE, IMAGE_MIME_TYPE, IMAGE_FILENAME, IMAGE_CHARSET, IMAGE_LAST_UPDATED) VALUES (6,'Boy''s Socks (Grey)',19.16,NULL,NULL,NULL,NULL);
INSERT INTO PRODUCTS (PRODUCT_ID, PRODUCT_NAME, UNIT_PRICE, IMAGE_MIME_TYPE, IMAGE_FILENAME, IMAGE_CHARSET, IMAGE_LAST_UPDATED) VALUES (7,'Boy''s Socks (Black)',19.58,NULL,NULL,NULL,NULL);
INSERT INTO PRODUCTS (PRODUCT_ID, PRODUCT_NAME, UNIT_PRICE, IMAGE_MIME_TYPE, IMAGE_FILENAME, IMAGE_CHARSET, IMAGE_LAST_UPDATED) VALUES (8,'Boy''s Coat (Brown)',21.16,NULL,NULL,NULL,NULL);
INSERT INTO PRODUCTS (PRODUCT_ID, PRODUCT_NAME, UNIT_PRICE, IMAGE_MIME_TYPE, IMAGE_FILENAME, IMAGE_CHARSET, IMAGE_LAST_UPDATED) VALUES (15,'Girl''s Coat (Blue)',13.09,NULL,NULL,NULL,NULL);
INSERT INTO PRODUCTS (PRODUCT_ID, PRODUCT_NAME, UNIT_PRICE, IMAGE_MIME_TYPE, IMAGE_FILENAME, IMAGE_CHARSET, IMAGE_LAST_UPDATED) VALUES (16,'Women''s Socks (Grey)',39.89,NULL,NULL,NULL,NULL);

INSERT INTO STORES (STORE_ID, STORE_NAME, WEB_ADDRESS, PHYSICAL_ADDRESS, LATITUDE, LONGITUDE, LOGO_MIME_TYPE, LOGO_FILENAME, LOGO_CHARSET, LOGO_LAST_UPDATED) VALUES (1,'Online','https://www.example.com',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO STORES (STORE_ID, STORE_NAME, WEB_ADDRESS, PHYSICAL_ADDRESS, LATITUDE, LONGITUDE, LOGO_MIME_TYPE, LOGO_FILENAME, LOGO_CHARSET, LOGO_LAST_UPDATED) VALUES (2,'San Francisco',NULL,'Redwood Shores 500 Oracle Parkway Redwood Shores, CA 94065',37.529395,-122.267237,NULL,NULL,NULL,NULL);
INSERT INTO STORES (STORE_ID, STORE_NAME, WEB_ADDRESS, PHYSICAL_ADDRESS, LATITUDE, LONGITUDE, LOGO_MIME_TYPE, LOGO_FILENAME, LOGO_CHARSET, LOGO_LAST_UPDATED) VALUES (3,'Seattle',NULL,'1501 Fourth Avenue Suite 1800 Seattle, WA 98101',47.6053,-122.33221,NULL,NULL,NULL,NULL);
INSERT INTO STORES (STORE_ID, STORE_NAME, WEB_ADDRESS, PHYSICAL_ADDRESS, LATITUDE, LONGITUDE, LOGO_MIME_TYPE, LOGO_FILENAME, LOGO_CHARSET, LOGO_LAST_UPDATED) VALUES (4,'New York City',NULL,'205 Lexington Ave 7th Floor New York, NY 10016',40.745216,-73.980518,NULL,NULL,NULL,NULL);
INSERT INTO STORES (STORE_ID, STORE_NAME, WEB_ADDRESS, PHYSICAL_ADDRESS, LATITUDE, LONGITUDE, LOGO_MIME_TYPE, LOGO_FILENAME, LOGO_CHARSET, LOGO_LAST_UPDATED) VALUES (5,'Chicago',NULL,'233 South Wacker Dr. 45th Floor Chicago, IL 60606',41.878751,-87.636675,NULL,NULL,NULL,NULL);
INSERT INTO STORES (STORE_ID, STORE_NAME, WEB_ADDRESS, PHYSICAL_ADDRESS, LATITUDE, LONGITUDE, LOGO_MIME_TYPE, LOGO_FILENAME, LOGO_CHARSET, LOGO_LAST_UPDATED) VALUES (6,'London',NULL,'One South Place London EC2M 2RB',51.519281,-.087296,NULL,NULL,NULL,NULL);
INSERT INTO STORES (STORE_ID, STORE_NAME, WEB_ADDRESS, PHYSICAL_ADDRESS, LATITUDE, LONGITUDE, LOGO_MIME_TYPE, LOGO_FILENAME, LOGO_CHARSET, LOGO_LAST_UPDATED) VALUES (7,'Bucharest',NULL,'Floreasca Park 43 Soseaua Pipera, corp B. Sector 2 Bucharest , 014254 RO',44.43225,26.10626,NULL,NULL,NULL,NULL);
INSERT INTO STORES (STORE_ID, STORE_NAME, WEB_ADDRESS, PHYSICAL_ADDRESS, LATITUDE, LONGITUDE, LOGO_MIME_TYPE, LOGO_FILENAME, LOGO_CHARSET, LOGO_LAST_UPDATED) VALUES (8,'Berlin',NULL,'Behrenstraße 42 (Humboldt Carré) 10117 Berlin',52.5161,13.3873,NULL,NULL,NULL,NULL);
INSERT INTO STORES (STORE_ID, STORE_NAME, WEB_ADDRESS, PHYSICAL_ADDRESS, LATITUDE, LONGITUDE, LOGO_MIME_TYPE, LOGO_FILENAME, LOGO_CHARSET, LOGO_LAST_UPDATED) VALUES (9,'Utrecht',NULL,'Hertogswetering 163-167, 3543 AS Utrecht, Netherlands',52.103263,5.061644,NULL,NULL,NULL,NULL);
INSERT INTO STORES (STORE_ID, STORE_NAME, WEB_ADDRESS, PHYSICAL_ADDRESS, LATITUDE, LONGITUDE, LOGO_MIME_TYPE, LOGO_FILENAME, LOGO_CHARSET, LOGO_LAST_UPDATED) VALUES (10,'Madrid',NULL,'C/ José Echegaray 6B Las Rozas 28230 Madrid',40.4929,-3.8737,NULL,NULL,NULL,NULL);

INSERT INTO CUSTOMERS (CUSTOMER_ID,FULL_NAME,EMAIL_ADDRESS) VALUES (1,'Tammy Bryant','tammy.bryant@internalmail');
INSERT INTO CUSTOMERS (CUSTOMER_ID,FULL_NAME,EMAIL_ADDRESS) VALUES (2,'Roy White','roy.white@internalmail');
INSERT INTO CUSTOMERS (CUSTOMER_ID,FULL_NAME,EMAIL_ADDRESS) VALUES (3,'Gary Jenkins','gary.jenkins@internalmail');
INSERT INTO CUSTOMERS (CUSTOMER_ID,FULL_NAME,EMAIL_ADDRESS) VALUES (4,'Victor Morris','victor.morris@internalmail');
INSERT INTO CUSTOMERS (CUSTOMER_ID,FULL_NAME,EMAIL_ADDRESS) VALUES (5,'Beverly Hughes','beverly.hughes@internalmail');
INSERT INTO CUSTOMERS (CUSTOMER_ID,FULL_NAME,EMAIL_ADDRESS) VALUES (6,'Evelyn Torres','evelyn.torres@internalmail');
INSERT INTO CUSTOMERS (CUSTOMER_ID,FULL_NAME,EMAIL_ADDRESS) VALUES (7,'Carl Lee','carl.lee@internalmail');
INSERT INTO CUSTOMERS (CUSTOMER_ID,FULL_NAME,EMAIL_ADDRESS) VALUES (8,'Douglas Flores','douglas.flores@internalmail');
INSERT INTO CUSTOMERS (CUSTOMER_ID,FULL_NAME,EMAIL_ADDRESS) VALUES (9,'Norma Robinson','norma.robinson@internalmail');
INSERT INTO CUSTOMERS (CUSTOMER_ID,FULL_NAME,EMAIL_ADDRESS) VALUES (10,'Gregory Sanchez','gregory.sanchez@internalmail');


INSERT_SQL
INSERT INTO ORDERS (ORDER_ID,ORDER_DATETIME,CUSTOMER_ID,ORDER_STATUS,STORE_ID) VALUES (1,TO_TIMESTAMP('2025-05-13 05:04:55.000000','YYYY-MM-DD HH24:MI:SS.FF6'),3,'CANCELLED',1);
INSERT INTO ORDERS (ORDER_ID,ORDER_DATETIME,CUSTOMER_ID,ORDER_STATUS,STORE_ID) VALUES (2,TO_TIMESTAMP('2025-05-17 12:42:43.000000','YYYY-MM-DD HH24:MI:SS.FF6'),45,'COMPLETE',1);
INSERT INTO ORDERS (ORDER_ID,ORDER_DATETIME,CUSTOMER_ID,ORDER_STATUS,STORE_ID) VALUES (3,TO_TIMESTAMP('2025-05-18 15:01:40.000000','YYYY-MM-DD HH24:MI:SS.FF6'),18,'COMPLETE',1);
INSERT INTO ORDERS (ORDER_ID,ORDER_DATETIME,CUSTOMER_ID,ORDER_STATUS,STORE_ID) VALUES (4,TO_TIMESTAMP('2025-05-19 05:28:09.000000','YYYY-MM-DD HH24:MI:SS.FF6'),45,'COMPLETE',1);
INSERT INTO ORDERS (ORDER_ID,ORDER_DATETIME,CUSTOMER_ID,ORDER_STATUS,STORE_ID) VALUES (5,TO_TIMESTAMP('2025-05-20 09:46:03.000000','YYYY-MM-DD HH24:MI:SS.FF6'),2,'COMPLETE',1);
INSERT INTO ORDERS (ORDER_ID,ORDER_DATETIME,CUSTOMER_ID,ORDER_STATUS,STORE_ID) VALUES (6,TO_TIMESTAMP('2025-05-22 11:56:21.000000','YYYY-MM-DD HH24:MI:SS.FF6'),74,'COMPLETE',1);
INSERT INTO ORDERS (ORDER_ID,ORDER_DATETIME,CUSTOMER_ID,ORDER_STATUS,STORE_ID) VALUES (7,TO_TIMESTAMP('2025-05-30 16:41:44.000000','YYYY-MM-DD HH24:MI:SS.FF6'),9,'COMPLETE',1);
INSERT INTO ORDERS (ORDER_ID,ORDER_DATETIME,CUSTOMER_ID,ORDER_STATUS,STORE_ID) VALUES (8,TO_TIMESTAMP('2025-05-31 06:45:25.000000','YYYY-MM-DD HH24:MI:SS.FF6'),109,'COMPLETE',1);
INSERT INTO ORDERS (ORDER_ID,ORDER_DATETIME,CUSTOMER_ID,ORDER_STATUS,STORE_ID) VALUES (9,TO_TIMESTAMP('2025-06-01 05:09:59.000000','YYYY-MM-DD HH24:MI:SS.FF6'),127,'COMPLETE',1);
INSERT INTO ORDERS (ORDER_ID,ORDER_DATETIME,CUSTOMER_ID,ORDER_STATUS,STORE_ID) VALUES (10,TO_TIMESTAMP('2025-06-01 05:46:43.000000','YYYY-MM-DD HH24:MI:SS.FF6'),106,'COMPLETE',1);

INSERT INTO ORDER_ITEMS (ORDER_ID,LINE_ITEM_ID,PRODUCT_ID,UNIT_PRICE,QUANTITY) VALUES (1,1,33,37,4);
INSERT INTO ORDER_ITEMS (ORDER_ID,LINE_ITEM_ID,PRODUCT_ID,UNIT_PRICE,QUANTITY) VALUES (1,2,11,30.69,2);
INSERT INTO ORDER_ITEMS (ORDER_ID,LINE_ITEM_ID,PRODUCT_ID,UNIT_PRICE,QUANTITY) VALUES (2,1,41,8.66,3);
INSERT INTO ORDER_ITEMS (ORDER_ID,LINE_ITEM_ID,PRODUCT_ID,UNIT_PRICE,QUANTITY) VALUES (2,2,32,5.65,5);
INSERT INTO ORDER_ITEMS (ORDER_ID,LINE_ITEM_ID,PRODUCT_ID,UNIT_PRICE,QUANTITY) VALUES (3,1,41,8.66,5);
INSERT INTO ORDER_ITEMS (ORDER_ID,LINE_ITEM_ID,PRODUCT_ID,UNIT_PRICE,QUANTITY) VALUES (4,1,20,28.21,2);
INSERT INTO ORDER_ITEMS (ORDER_ID,LINE_ITEM_ID,PRODUCT_ID,UNIT_PRICE,QUANTITY) VALUES (4,2,38,22.98,4);
INSERT INTO ORDER_ITEMS (ORDER_ID,LINE_ITEM_ID,PRODUCT_ID,UNIT_PRICE,QUANTITY) VALUES (4,3,46,39.16,4);
INSERT INTO ORDER_ITEMS (ORDER_ID,LINE_ITEM_ID,PRODUCT_ID,UNIT_PRICE,QUANTITY) VALUES (5,1,40,34.06,4);
INSERT INTO ORDER_ITEMS (ORDER_ID,LINE_ITEM_ID,PRODUCT_ID,UNIT_PRICE,QUANTITY) VALUES (5,2,32,5.65,3);