Rem
Rem  Customer Orders Management Applications DDL/DML
Rem
  CREATE TABLE "PRODUCTS" 
   (	"PRODUCT_ID" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 50 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"PRODUCT_NAME" VARCHAR2(255) NOT NULL ENABLE, 
	"UNIT_PRICE" NUMBER(10,2), 
	"PRODUCT_DETAILS" BLOB, 
	"PRODUCT_IMAGE" BLOB, 
	"IMAGE_MIME_TYPE" VARCHAR2(512), 
	"IMAGE_FILENAME" VARCHAR2(512), 
	"IMAGE_CHARSET" VARCHAR2(512), 
	"IMAGE_LAST_UPDATED" DATE, 
	 CONSTRAINT "PRODUCTS_PK" PRIMARY KEY ("PRODUCT_ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "PRODUCT_JSON_C" CHECK (product_details is json) ENABLE
   ) ;

  CREATE TABLE "STORES" 
   (	"STORE_ID" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 25 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"STORE_NAME" VARCHAR2(255) NOT NULL ENABLE, 
	"WEB_ADDRESS" VARCHAR2(100), 
	"PHYSICAL_ADDRESS" VARCHAR2(512), 
	"LATITUDE" NUMBER, 
	"LONGITUDE" NUMBER, 
	"LOGO" BLOB, 
	"LOGO_MIME_TYPE" VARCHAR2(512), 
	"LOGO_FILENAME" VARCHAR2(512), 
	"LOGO_CHARSET" VARCHAR2(512), 
	"LOGO_LAST_UPDATED" DATE, 
	 CONSTRAINT "STORES_PK" PRIMARY KEY ("STORE_ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "STORE_NAME_U" UNIQUE ("STORE_NAME")
  USING INDEX  ENABLE, 
	 CONSTRAINT "STORE_AT_LEAST_ONE_ADDRESS_C" CHECK (coalesce ( web_address, physical_address ) is not null) ENABLE
   ) ;

  CREATE TABLE "CUSTOMERS" 
   (	"CUSTOMER_ID" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 400 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"FULL_NAME" VARCHAR2(255) NOT NULL ENABLE, 
	"EMAIL_ADDRESS" VARCHAR2(255) NOT NULL ENABLE, 
	 CONSTRAINT "CUSTOMERS_PK" PRIMARY KEY ("CUSTOMER_ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "CUSTOMERS_EMAIL_U" UNIQUE ("EMAIL_ADDRESS")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "ORDERS" 
   (	"ORDER_ID" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 2000 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"ORDER_DATETIME" TIMESTAMP (6) NOT NULL ENABLE, 
	"CUSTOMER_ID" NUMBER NOT NULL ENABLE, 
	"ORDER_STATUS" VARCHAR2(10) NOT NULL ENABLE, 
	"STORE_ID" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "ORDERS_PK" PRIMARY KEY ("ORDER_ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "ORDER_STATUS_C" CHECK (order_status in ('CANCELLED','COMPLETE','OPEN','PAID','REFUNDED','SHIPPED')) ENABLE
   ) ;

  CREATE TABLE "ORDER_ITEMS" 
   (	"ORDER_ID" NUMBER NOT NULL ENABLE, 
	"LINE_ITEM_ID" NUMBER NOT NULL ENABLE, 
	"PRODUCT_ID" NUMBER NOT NULL ENABLE, 
	"UNIT_PRICE" NUMBER(10,2) NOT NULL ENABLE, 
	"QUANTITY" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "ORDER_ITEMS_PK" PRIMARY KEY ("ORDER_ID", "LINE_ITEM_ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "ORDER_ITEMS_PRODUCT_U" UNIQUE ("PRODUCT_ID", "ORDER_ID")
  USING INDEX  ENABLE
   ) ;

  CREATE INDEX "CUSTOMERS_NAME_I" ON "CUSTOMERS" ("FULL_NAME") 
  ;

  ALTER TABLE "ORDERS" ADD CONSTRAINT "ORDERS_CUSTOMER_ID_FK" FOREIGN KEY ("CUSTOMER_ID")
	  REFERENCES "CUSTOMERS" ("CUSTOMER_ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "ORDERS" ADD CONSTRAINT "ORDERS_STORE_ID_FK" FOREIGN KEY ("STORE_ID")
	  REFERENCES "STORES" ("STORE_ID") ON DELETE CASCADE ENABLE;

  CREATE INDEX "ORDERS_CUSTOMER_ID_I" ON "ORDERS" ("CUSTOMER_ID") 
  ;

  CREATE INDEX "ORDERS_STORE_ID_I" ON "ORDERS" ("STORE_ID") 
  ;

  ALTER TABLE "ORDER_ITEMS" ADD CONSTRAINT "ORDER_ITEMS_ORDER_ID_FK" FOREIGN KEY ("ORDER_ID")
	  REFERENCES "ORDERS" ("ORDER_ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "ORDER_ITEMS" ADD CONSTRAINT "ORDER_ITEMS_PRODUCT_ID_FK" FOREIGN KEY ("PRODUCT_ID")
	  REFERENCES "PRODUCTS" ("PRODUCT_ID") ON DELETE CASCADE ENABLE;


  CREATE OR REPLACE FORCE EDITIONABLE VIEW "CUSTOMER_ORDER_PRODUCTS" ("ORDER_ID", "ORDER_DATETIME", "ORDER_STATUS", "CUSTOMER_ID", "EMAIL_ADDRESS", "FULL_NAME", "ORDER_TOTAL", "ITEMS") AS 
  select o.order_id
,      o.order_datetime
,      o.order_status
,      c.customer_id
,      c.email_address
,      c.full_name
,      sum ( oi.quantity * oi.unit_price ) order_total
,      listagg (p.product_name, ', ' on overflow truncate '...' with count)
         within group ( order by oi.line_item_id ) items
from orders o
join order_items oi
  on o.order_id = oi.order_id
join customers c
  on o.customer_id = c.customer_id
join products p
  on oi.product_id = p.product_id
group by o.order_id
,        o.order_datetime
,        o.order_status
,        c.customer_id
,        c.email_address
,        c.full_name;

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "PRODUCT_ORDERS" ("PRODUCT_NAME", "ORDER_STATUS", "TOTAL_SALES", "ORDER_COUNT") AS 
  select p.product_name
,      o.order_status
,      sum ( oi.quantity * oi.unit_price ) total_sales
,      count (*) order_count
from orders o
join order_items oi
  on o.order_id = oi.order_id
join customers c
  on o.customer_id = c.customer_id
join products p
  on oi.product_id = p.product_id
group by p.product_name
,        o.order_status;

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "PRODUCT_REVIEWS" ("PRODUCT_NAME", "RATING", "AVG_RATING", "REVIEW") AS 
  select p.product_name
,      r.rating
,      round (avg (r.rating) over (partition by product_name), 2) avg_rating
,      r.review
from products p
,    json_table
       (p.product_details, '$'
        columns (nested path '$.reviews[*]'
                 columns (  rating number path '$.rating'
                          , review varchar2(4000) path '$.review'
                         )
                )
       ) r;

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "STORE_ORDERS" ("TOTAL", "STORE_NAME", "ADDRESS", "LATITUDE", "LONGITUDE", "ORDER_STATUS", "ORDER_COUNT", "TOTAL_SALES") AS 
  select case
         grouping_id ( store_name, order_status )
           when 1 then 'STORE TOTAL'
           when 2 then 'STATUS TOTAL'
           when 3 then 'GRAND TOTAL'
       end total
,      s.store_name
,      coalesce ( s.web_address, s.physical_address ) address
,      s.latitude
,      s.longitude
,      o.order_status
,      count ( distinct o.order_id ) order_count
,      sum ( oi.quantity * oi.unit_price ) total_sales
from stores s
join orders o
  on s.store_id = o.store_id
join order_items oi
  on o.order_id = oi.order_id
group by grouping sets (  (s.store_name, coalesce(s.web_address,s.physical_address), s.latitude, s.longitude)
                        , (s.store_name, coalesce(s.web_address,s.physical_address), s.latitude, s.longitude, o.order_status)
                        , o.order_status
                        , ()
                       );

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "STORE_ORDERS_STATUS" ("STORE_NAME", "ADDRESS", "LATITUDE", "LONGITUDE", "ORDER_STATUS", "ORDER_COUNT", "TOTAL_SALES") AS 
  select s.store_name
,      coalesce ( s.web_address, s.physical_address ) address
,      s.latitude
,      s.longitude
,      o.order_status
,      count ( distinct o.order_id ) order_count
,      sum ( oi.quantity * oi.unit_price ) total_sales
from stores s
join orders o
  on s.store_id = o.store_id
join order_items oi
  on o.order_id = oi.order_id
group by s.store_name, coalesce ( s.web_address, s.physical_address ), s.latitude, s.longitude, o.order_status;


